### ISSUE TITLE
Paygreen api authentification

### ISSUE THREAD

**Issue by quentinlamamy** [Hraph/PaygreenApiPHP#1]
Hi Folks,

I see in the source code yo uare using oAuth but in the official documentation they said to only use a shop id and a key to authenticate during api call. They have change something or ommit something in the doc ?

**Comment by Hraph** [comment]
Hi Quentin,

As written in the readme, this code is a generated with Swagger OpenAPI Codegen using the original PayGreen specs (rearranged a bit because their documentation sucks...)
Don't worry if you see some OAuth implementation it's just some boilerplate code and PayGreen is definitely only using the not so secure id/key authentication. 

If you want to see this library in action you can take a look at this project: https://github.com/Hraph/SyliusPaygreenPlugin/blob/master/src/Client/PaygreenApiClient.php

Thanks for contacting me.
