### ISSUE TITLE
Unable deserialize : Invalid array 'string' 

### ISSUE THREAD

**Issue by altivec** [Hraph/PaygreenApiPHP#3]
Hi, I am testing your wonderfull implementation for PayGreen API but with my first call to this method apiIdentifiantPaymenttypeGet() I get an error.
API call is made correctly, I receveive a valid answer from paygreen with all payment datas but there is a error with deserialize : Invalid array 'string' 

Any idea ?

Thanks for your help.

**Comment by Hraph** [comment]
Hello Clauzel, thanks for your commitment.
I've also encountered this issue with the v1.1.0. With this version the deserialization is more strict and if the Paygreen API specification is not well defined, it can easily fail. If you wish you can use the v1.0.0 while I'm correcting it.
Thanks

**Comment by Hraph** [comment]
I just published a new version (v1.1.1) that resolves this issue. Could you tell me if you managed to get it work?

**Comment by altivec** [comment]
> I just published a new version (v1.1.1) that resolves this issue. Could you tell me if you managed to get it work?

Hi, thanks for your reply, but I get the same error with 1.1.1, even with the 1.0.0 version ...

**Comment by Hraph** [comment]
I personally get a Paygreeen 403 error (`{"success":false,"message":"Unknow Shop ID","code":991,"data":null}`) because my account is in sandbod and not configured but any serialization error with the method `apiIdentifiantPaymenttypeGet`

**Comment by Hraph** [comment]
I personally get a Paygreeen 403 error (`{"success":false,"message":"Unknow Shop ID","code":991,"data":null}`) because my account is in sandbox and not configured but any deserialization error with the method `apiIdentifiantPaymenttypeGet`. I don't think I'll be able to reproduce the error if it's a particular response from the paygreen api. It would be nice if you could debug it and tell me which property is not working in the `ObjectSerializer` class.
